### ISSUE TITLE
section.updates-container text is blurry on Firefox

### ISSUE THREAD

**Issue by themaxdavitt** [kstenerud/concise-encoding#11]
On the website, the text in the element identified by selector `section.updates-container` looks fine on Chrome, but looks blurry on Firefox 85.0.2 (on Windows):

![Blurry text in element on Firefox 85.0.2](https://user-images.githubusercontent.com/27709025/109180441-e2278400-7758-11eb-97c4-f6693c5be83d.png)

I'm guessing this is related to the `filter` rule you're using to create the shadow underneath it. Could `box-shadow` be used instead?

**Comment by kstenerud** [comment]
Oh wow that's so strange! On Firefox 86.0 on Windows it looks crystal clear.
I'll see if I can get the same effect the other way though. Thanks!

**Comment by kstenerud** [comment]
OK, I've changed the update container to use a box shadow since it doesn't have a hover effect anyway. See if that fixes it?

**Comment by themaxdavitt** [comment]
Strange indeed! Maybe it was my font rendering settings or something? It looks much better now though, thank you! 

![image](https://user-images.githubusercontent.com/27709025/109216780-f8e2d080-7782-11eb-8264-7e30767c3b0c.png)
