### ISSUE TITLE
Markup example uses semicolon (instead of comma)

### ISSUE THREAD

**Issue by kengruven** [kstenerud/concise-encoding#17]
The [Markup example in the CE spec](https://github.com/kstenerud/concise-encoding/blob/master/ce-structure.md#markup) fails to parse with enctool:

```
$ cat | ./enctool convert -df cte
c1 <View;
    <Image src=|r images/avatar-image.jpg|>
    <Text,
        Hello! Please choose a name!
    >
    /* <HRule style=thin> */
    <TextInput id=name style={height=40 borderColor=gray}, Name me! >
>
coffset 8 (line 1, col 9): Unexpected [;]
```

Eventually, I found in [the CTE spec](https://github.com/kstenerud/concise-encoding/blob/master/cte-specification.md#markup) a similar example but with a comma used instead of a semicolon, and that seems to work fine.

It looks like this is just a typo, or maybe the spec got changed from `;` to `,` at some point and this example didn't get updated.

**Comment by kstenerud** [comment]
Whoops! Yeah the spec used to use `|`, then `:`, then `;`, then `,` :)

**Comment by kstenerud** [comment]
Fixed in latest commit.
