### ISSUE TITLE
bfloat16 example is over-precise

### ISSUE THREAD

**Issue by kengruven** [kstenerud/concise-encoding#18]
The bfloat16 example in the CBE spec reads:

> [70 af 44] = 0x1.5e4p+10

This is not exactly wrong, but it's a little strange.  The bfloat16 data type holds only 7 bits of mantissa.  This value has 3 digits past the (hexa?)decimal point.  In binary, they would be 0101 1110 0100.  In other words, this number as written requires at least 10 bits of mantissa, and bfloat16 doesn't have that many.

As a float32 or float64, this value would be exactly (1+5/16+14/256+4/4096)*2^10=1401.  Squeezed into a bfloat16, though, it's (1+5/16+14/256)*2^10=1400.

This could be confusing to implementors, especially if they're in a language without a native bfloat16 data type and have to resort to truncating float32 bit patterns.

I'd suggest rewriting this example as:

> [70 af 44] = 0x1.5ep+10

**Comment by kstenerud** [comment]
Good catch!

**Comment by kstenerud** [comment]
Fixed in latest commit.
