### ISSUE TITLE
Unquoted strings

### ISSUE THREAD

**Issue by kengruven** [kstenerud/concise-encoding#20]
There are a number of places in the CTE spec that appear to use unquoted strings, but this is invalid with enctool, and gives a strange error ("Expected a UUID (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)").

- the "General" examples: `c1 [a b c]`, `c1 {a=1 b=2 c=3}`
- the "Resource IDs support concatenation" example
- both "Pretend that this is a huge string" examples (Marker; Reference)
- the "Combined Objects" example
- the "Pretty Printing" examples `[a b c d]`, "aliens", `{a=b c=d}`

It looks like this feature was removed in 478461f4.

**Comment by kstenerud** [comment]
OK, hopefully I've got them all now!

**Comment by kengruven** [comment]
One more?  `resources = [`…

**Comment by kstenerud** [comment]
OK fixed :)
