### ISSUE TITLE
Text Safety rules

### ISSUE THREAD

**Issue by kengruven** [kstenerud/concise-encoding#21]
I'm trying to implement a function to check a string for [Text Safety](https://github.com/kstenerud/concise-encoding/blob/master/ce-structure.md#text-safety).  There's a big list of characters in the CE spec which are considered "unsafe", but I'm not sure how to interpret all of these.

- "Unassigned characters": looks like General_Category "Cn"
- "Reserved characters": according to <https://en.wikipedia.org/wiki/Unicode_character_property>, this is a subset of "unassigned"?
- "Private characters": General_Category "Co"?
- "Unprintable characters": possibly not well defined (according to https://stackoverflow.com/questions/3770117/), and I can't tell what this might refer to besides unassigned/zero-width/control characters, which are already covered elsewhere; the only other interpretation I can think of is something like category "Z" ("Separator") which are invisible, but that would include U+0020 (space), and clearly CE doesn't require every space to be escaped
- "Surrogate pairs": General_Category "Cs"
- "Byte order mark (U+FEFF)": this is zero-width, so it's redundant with the next line
- "Zero-width characters": according to <https://www.ptiglobal.com/2018/04/26/the-beauty-of-unicode-zero-width-characters/> there are 5, and all of them appear to be General_Category "Cf"
- "Line breaks, except for LF (u+000a), and CR (u+000d)": <https://en.wikipedia.org/wiki/Newline#Unicode> lists 8 (including the CR+LF combination which would be redundant here) -- most are General_Category "Cc", but U+2028 is "Zl" and U+2029 is "Zp"
- "Control characters, except for TAB (u+0009), LF (u+000a), and CR (u+000d)": it looks like General_Category "C" codepoints are all considered "Control", so this makes most of the previous 8 lines redundant

When I remove the redundancy and ambiguity, it looks like this list is simply a roundabout way to say that CE's "text-unsafe" characters are:
- General_Category "C", "Zl", and "Zp"
- except codepoints U+000A (LF), U+000D (CR), and U+0009 (TAB) are safe

Am I reading that right?

**Comment by kstenerud** [comment]
Yup, that's definitely a more succinct way to put it!

I'll update the spec to match :)

**Comment by kstenerud** [comment]
https://github.com/kstenerud/concise-encoding/commit/a7323b2949c139e4a4fcaef6690652408d9b22c3
