### ISSUE TITLE
Comment/Relationship codes are inconsistent

### ISSUE THREAD

**Issue by kengruven** [kstenerud/concise-encoding#25]
- The table [here](https://github.com/kstenerud/concise-encoding/blob/master/cbe-specification.md#type-field) uses 76 for Relationship, and 77 for Comment
- The examples [here](https://github.com/kstenerud/concise-encoding/blob/master/cbe-specification.md#relationship) use `[77]` for Relationship
- The examples [here](https://github.com/kstenerud/concise-encoding/blob/master/cbe-specification.md#comment) use `[76]` for Comment

As of today, enctool seems to follow the table, not the examples.

**Comment by kstenerud** [comment]
When the examples contradict the table, the examples are wrong (the table is authoritative). I've been updating them so much after each type code reshuffle that parts keep getting missed :/

https://github.com/kstenerud/concise-encoding/commit/2b4686dcb70cef86f512915834e3790a1e2e5a4b
