### ISSUE TITLE
Can't use nan in f32 array

### ISSUE THREAD

**Issue by kengruven** [kstenerud/concise-encoding#27]
Trying to put a nan/inf into a float array fails:

```
echo 'c1 |f32 123.456 nan|' | ./enctool convert -df cte
c0
offset 16 (line 1, col 17): unexpected [n] while decoding float
```

I don't see any rule in the spec that would prohibit this.

**Comment by kstenerud** [comment]
That's an oversight. It should support nan, snan, and inf.

**Comment by kstenerud** [comment]
Support added https://github.com/kstenerud/go-concise-encoding/commit/d12861413629841a95e2e3ddf3d267349a96e9db

Also wrote a note about it https://github.com/kstenerud/concise-encoding/commit/e5dc45b6c5094633606feabc00223b7c82b856ec

**Comment by kengruven** [comment]
From reading the spec, I would have assumed that an implied prefix would cause special floats like `nan` to fail.  It says "all values MUST be considered to have an implicit prefix", and "0xnan" isn't a valid f32, for example.

I'm totally fine with saying that special floats can bypass the prefix rule (which is quite convenient), as long as the spec points out this special case.

Other than that, looks good.

**Comment by kstenerud** [comment]
https://github.com/kstenerud/concise-encoding/commit/0c17006d4254b3694cf09530ce933f394b2f8d22
