### ISSUE TITLE
Tree container?

### ISSUE THREAD

**Issue by kstenerud** [kstenerud/concise-encoding#33]
This is probably a crazy idea, but I thought I'd put it out there to get peoples thoughts on it. This won't go into CE version 1, but if there's enough interest, I'd consider putting it into version 2.

Basically, a generic tree structure such as for example:

	       .------------
	      /|\           \
	     / | \           \
	    /  |  \           \
	  "a" "b"  .           .
	          /|\         / \
	         / | \       /   \
	        /  |  \    "f"    .
	      "c" "d" "e"        / \
	                       "g" "h"

which would be represented (in CTE) by:

    ("a" "b" ("c" "d" "e") ("f" ("g" "h")))

TBH I can't think of any situation  in 25 years professionally where I've thought to myself "I really need to transmit this tree structure between machines!" We all agree that tree structures are useful in computing, but the idea of *transmitting* tree structures just seems weird.

So I'm looking at this and saying "Yeah, this would be super easy to implement and it looks nice, but would anyone ever actually **use** it???" I don't know. Do we need to have the possibility before someone finds a use? Or is it just not useful to transmit tree structures?

**Comment by kengruven** [comment]
Sure, I need to store tree structures, but how is this different from the list `["a" "b" ["c" "d" "e"] ["f" ["g" "h"]]]`?

Semantics, perhaps, but the interpretation of the data is already up to the reader.  Most values I want to encode in CE don't contain complete meaning unless the context has previously been agreed upon, or communicated out-of-band.

(As an implementor, I wouldn't say this looks super easy to me.  I have many questions, starting with: Do only leaf nodes get values?)

Conceptually, is there any case where I'd want to be able to encode *either* a tree or a (nested) list, in the same location in the schema, without having to provide any indication of which type it is?

That's basically how Lisp has always worked, and I can't say I've ever noticed this limitation being a problem.

**Comment by kstenerud** [comment]
I've spent a few days noodling on it. The basic issue is that a tree requires more information than a list can provide. Each node requires both a value and a collection of child nodes. In the above example, the node containing the children "c", "d", and "e" doesn't itself have a value (like "z"), nor could it because there's no mechanism to store such a value.

With only lists, there's no way to represent nodes "a" or "c" below because they have both a value *and* children:
```
  a
 / \
b   c
   / \
  d   e
```

Tree is actually the last remaining [fundamental data type](https://en.wikipedia.org/wiki/List_of_data_structures) in computer science that isn't easily represented in a portable serialized form. I haven't been able to find any existing serialized tree representations that aren't difficult for a human to read or write (or both!)

But after a bit of playing around, it turns out that if you order your nodes with a slight twist from a standard pre-order traversal, there's a way to write it that's actually not too bad. You just tilt your head a bit to the left and it kinda looks like a tree! My current draft:

### Node

A node is the basic building block for all tree structures. It consists of:

* A value (any object, including a container).
* A collection of zero or more children, which **MUST** all be nodes.

Nodes **MUST** be written using a "mirrored" pre-order traversal (depth-first, but NRL instead of NLR). This ensures that the tree looks similar when viewed in text form (CTE), except that it appears somewhat rotated with depth growing diagonally right-downward instead of down, and depth-peer nodes are aligned vertically instead of horizontally.

A node begins with an opening parenthesis `(`, contains a value (object) followed by zero or more child nodes, and is closed with a closing parenthesis `)`.

**Example**:

```cte
c1
// The tree structure:
//       2
//      / \
//     7   5
//    /|\   \
//   2 1 6   9
//  / \       \
// 5   8       4
//
(2
    (5
        (9
            (4)
        )
    )
    (7
        (6)
        (1)
        (2
            (8)
            (5)
        )
    )
)
```

**Comment by kengruven** [comment]
Sorry, I'm still not understanding.

> In the above example, the node containing the children "c", "d", and "e" doesn't itself have a value (like "z"), nor could it because there's no mechanism to store such a value.

While it's literally true that s-exps are simply anonymous nodes with a CAR and a CDR, I think that proper lists (the subset used by this proposal, and by Amazon Ion) are generally understood to mean a tree structure where the first element is the parent and subsequent elements are the children of that parent.  I read `(+ x y z)` as the parent `+` and children `x`, `y`, and `z` — not the rightward branching binary tree with structure `(+ . (x . (y . (z . nil))))`.  After all, taken literally, s-exps always have exactly 2 children of each parent, too, which is kind of useless here.

With the original example, this would look like: `["." "a" "b" ["z" "c" "d" "e"] ["." "f" ["." "g" "h"]]]`.

I suppose without a syntactic distinction between "node" and "list", this means you can't use lists as tree nodes, without some extra indicator of type.  But as I said, that already happens all the time in CE (and JSON, and …) with almost every other type.  It seems strange to add a whole new collection type to solve this potential issue for one type (which I can't recall ever actually running into).  I think I'd rather have metadata maps come back, which would allow me to fix this problem for all types, not just trees/lists.

> Using only lists, there's no way to represent nodes "a" or "c" in the tree below because they have both a value and children

I see this as the expression `(a b (c d e))`, so I'd write it in CTE as `["a" "b" ["c" "d" "e"]]`.

> Tree is actually the last remaining fundamental data type in computer science that isn't easily represented in a portable serialized form.

So arbitrary graphs are easily represented in portable serialized form?  Or are trees more fundamental than graphs?  I'm afraid I don't understand what this sentence is trying to convey.

> Nodes MUST be written using a "mirrored" pre-order traversal (depth-first, but node-right-left instead of node-left-right).

I don't understand why these trees are backwards.  It just seems like extra confusion for people, and extra complexity (and likely a performance penalty) for implementors.

**Comment by kstenerud** [comment]
Technically speaking, a tree could be represented using lists with specially designated positions (i.e. first position is always the "value" of the node). This can be done with the help of a schema or metadata, but to me these sorts of tricks feel like hacks to coerce the data into a special meaning that the enclosing type wasn't originally designed for.

Schema/metadata hacks are generally fine for more esoteric data types, but as more of your fundamental and commonly used types require this trickery, the format becomes more and more cumbersome to read and write. Technically speaking, you could encode any data type and structure into XML, because all you really *need* in order to represent anything in computer science is a map type, a string type, and a schema to explain how to interpret everything.

So what I'm trying to sort out in CE is: where is the optimal balance between fundamental types and synthetic ones?

Currently we have:

### [Data Types](https://en.wikipedia.org/wiki/Data_type)

#### Supported directly
- Boolean
- Integer
- Floating point
- String
- List/Array
- Map
- Pointer/reference (marker/reference)
- Date/time
- Null
- Commonly used special purpose types such as UUID, markup, media, relationship

#### To be supported via schemas (because they're not as common, and can be partially understood using lists & maps):
- Record
- Union
- Enumerated type
- Set
- Bag

#### To be supported in the (future) RPC spec:
- Function

Node would fill in the hole for trees and graphs by unambiguously signifying "I have a value and links to other nodes". You could even have cyclic graphs with the help of markers/references. The default would be tree, and graphs would require schema help since they're so free-form that one can't have a canonical "graph".

> With the original example, this would look like: ["." "a" "b" ["z" "c" "d" "e"] ["." "f" ["." "g" "h"]]].

If I understand correctly, that's the tree:

```
  .-------
 /|\      \
a b z      .
   /|\    / \
  c d e  f   .
            / \
           g   h
```

As the tree gets bigger, it gets harder to read the serialized form, which is why I wanted to come up with a "visual" representation. This was also the reasoning behind the "mirrored" encoding: so that when viewed visually, rotated in the text form, it actually does (sort of) look like the tree it represents, with top-down depth, "left" nodes to the left, and "right" nodes to the right.


```
(nil
	(nil
		(nil
			("h")
			("g")
		)
		("f")
	)
	("z"
		("e")
		("d")
		("c")
	)
	("b")
	("a")
)
```

To visualize the above tree, you'd imagine it rotated to the right. Now top-down is depth, and left-right is, well, left-to-right.
![Screenshot at 2021-07-12 07-39-44](https://user-images.githubusercontent.com/245857/125238079-fecaef80-e2e6-11eb-9ffb-035fac0df295.png)

Viewing this rotated, it's fairly easy to see that it's a tree with an anonymous root node, containing (left-to-right) "a", "b", then "z" with sub-nodes, then an anonymous node with sub-nodes. Each depth level reads left-to-right when viewed rotated.

```
  .-------
 /|\      \
a b z      .
   /|\    / \
  c d e  f   .
            / \
           g   h
```

If it were written in the traditional order, the on-page rotated visualization would look reversed right-to-left compared to the original tree:

```
(nil
	("a")
	("b")
	("z"
		("c")
		("d")
		("e")
	)
	(nil
		("f")
		(nil
			("g")
			("h")
		)
	)
)
```
![Screenshot at 2021-07-12 07-40-01](https://user-images.githubusercontent.com/245857/125238092-05f1fd80-e2e7-11eb-8781-5665e56b9e76.png)

```
  .-------
 /|\      \
a b z      .
   /|\    / \
  c d e  f   .
            / \
           g   h
```

> I don't understand why these trees are backwards. It just seems like extra confusion for people, and extra complexity (and likely a performance penalty) for implementors.

Encoding/decoding complexity wouldn't be much affected by the right-left ordering since it's just a matter of reversing the visit order (you're still going depth-first). My main goal is to make it easy for a human to scan visually, spatially.

**Comment by kstenerud** [comment]
Here's the next draft:

### Node

A node is a basic building block for tree and graph structures. It consists of:

* A value (any object, including a container).
* A collection of zero or more child nodes (node or reference to node).

Trees **MUST** be ordered using a **depth-first**, **node-right-left** order, which ensures that the CTE representation looks visually like the actual tree structure it describes when rotated 90 degrees clockwise:

```cte
c1
(2
    (7
        (2)
        (1)
        (6
            (5)
            (8)
        )
    )
    (5
        (9
            (4)
        )
    )
)

```

When rotated 90 degrees clockwise, one can recognize the tree structure this represents:

![tree-rotated](https://user-images.githubusercontent.com/245857/125573396-b2aadd90-5c76-423c-ae96-1cb008755649.png)


```
      2
     / \
    5   7
   /   /|\
  9   6 1 2
 /   / \
4   8   5
```

**Comment by kstenerud** [comment]
Aha! I think I've got it!

By relaxing the type constraints on the `relationship` type, it basically becomes a generic graph edge. Edges and nodes can describe all forms of graphs! And as a bonus, all type restrictions are now gone (in edge and in node), making it less complicated in the process! Now CE natively supports all fundamental CS data types :)

### Edge

An edge describes a relationship between vertices in a graph. It is composed of three parts:

 * A **source**, which is the first vertex of the edge being described. This will usually be either a [reference](#reference) to an existing object, or a [resource ID](#resource-identifier).
 * A **description**, which describes the relationship (edge) between the source and destination. This implementation-dependent object can contain information such as weight, directionality, or other arbitrary data. If the edge has no properties, use [nil](#nil).
 * A **destination**, which is the second vertex of the edge being described.

Directionality is from the source to the destination, unless the description or schema specifies otherwise.

Because graphs can take so many forms, there is no default interpretation for edges. Both sender and receiver **MUST** have a common understanding of what the graph edges represent, and how to interpret the data. For directed graphs with no edge descriptions, it's better to use [nodes](#node) instead.

#### Example

Edges can describe many kinds of graphs, even [RDF-style](https://en.wikipedia.org/wiki/Resource_Description_Framework) edges of a semantic graph (where the source, description and destination represent the subject, predicate and object of the semantic relationships):

```cte
c1 [
    @(
        @"https://springfield.gov/people#homer_simpson"
        @"https://example.org/wife"
        @"https://springfield.gov/people#marge_simpson"
    )
    @(
        @"https://springfield.gov/people#homer_simpson"
        @"https://example.org/employer"
        @"https://springfield.gov/employers/nuclear_power_plant"
    )
]
```

From this data, we understand that Homer Simpson's wife is Marge Simpson, and that Homer Simpson's employer is the nuclear power plant.

More complex graph data can be succinctly represented by mixing in other CE features such as [references](#reference), [lists](#list), and [maps](#map).

```cte
c1 {
    "resources" = [
        &people:@"https://springfield.gov/people#"
        &mp:@"https://mypredicates.org/"
        &mo:@"https://myobjects.org/"
    ]

    $people:"homer_simpson" = {
        $mp:"wife" = $people:"marge_simpson"
        $mp:"regrets" = [
            $firing
            $forgotten_birthday
        ]
        $mp:"troubles" = $troubles
    }

    "graph edges" = [
        &marge_birthday:@(
            $people:"marge_simpson"
            $mp:"birthday"
            1956-10-01
        )
        &forgotten_birthday:@(
            $people:"homer_simpson"
            $mp:"forgot"
            $marge_birthday
        )
        &firing:@(
            $people:"montgomery_burns"
            $mp:"fired"
            $people:"homer_simpson"
        )

        // Multiple subjects
        &troubles:@(
            [$firing $forgotten_birthday]
            $mp:"contribute"
            $mo:"marital_strife"
        )
    ]
}
```


### Node

A node is the basic building block for unweighted directed graphs. It consists of:

 * A value (any object).
 * A collection of zero or more children (directionality is always from the node to its children).

If a child is not of type node, it is treated as though it were the value portion of a node with no children.

**Hint**: If the graph is cyclic, use [references](#reference) to nodes to represent the cycles.

Unless otherwise specified by a schema, the default interpretation of the data is a tree ordered using a **depth-first**, **node-right-left** order. This ensures that the pretty printed CTE representation looks like the actual tree structure it describes when rotated 90 degrees clockwise:

```cte
c1
(2
    (7
        2
        1
        (6
            5
            8
        )
    )
    (5
        (9
            4
        )
    )
)

```

When rotated 90 degrees clockwise, one can recognize the tree structure this represents:

![tree-rotated](https://user-images.githubusercontent.com/245857/125991926-1b0dbc70-2271-47a7-8bb1-8570c8280fb8.png)


```
      2
     / \
    5   7
   /   /|\
  9   6 1 2
 /   / \
4   8   5
```
