### ISSUE TITLE
Comments in arrays?

### ISSUE THREAD

**Issue by kengruven** [kstenerud/concise-encoding#36]
Looking at https://github.com/kstenerud/concise-encoding/blob/master/ce-structure.md#comment, it says "Comments are allowed anywhere in a CTE document except ...", and lists "Inside of a string-like array type", and makes no mention of any other array types.

But then the example immediately below that says:

```
"data" =
    // Comment before some binary data (but not inside it)
    |u8x 01 02 03 04 05 06 07 08 09 0a|
```

which is ambiguous.  My initial reading was that this implies that comments aren't allowed inside (non-string-like) arrays, but I could also interpret this as simply clarifying that this particular comment object is not structurally inside this array.

Empirically, it doesn't seem to be allowed right now:

```
$ echo 'c1 |u8x /* foo */ 1 2 3|' | ./enctool convert -df cte
c0
offset 8 (line 1, col 9): unexpected character / at end of hex
```

**Comment by kstenerud** [comment]
I've updated the description to hopefully make things more clear: https://github.com/kstenerud/concise-encoding/blob/master/ce-structure.md#comment

Also updated [string-like array](https://github.com/kstenerud/concise-encoding/blob/master/ce-structure.md#string-like-arrays) to make it more descriptive.

I've also updated the example. The go implementation hasn't been updated yet.

**Comment by kstenerud** [comment]
Test case:

```cte
{
    "name" = "Comments in arrays"
    "issue link" = @"https://github.com/kstenerud/concise-encoding/issues/36"
    "cte" = "\.%%%%
c0 |u8x /* foo */ 1 2 3|
    %%%%"
    "events" = [
                    "bd" "v 0"
                        "au8b" "com t  foo " "ac 3 f" "ad 1 2 3"
                    "ed"
                ]
    "from"   = ["t"]
    "to"     = ["e"]
}
```

**Comment by kstenerud** [comment]
Fixed in https://github.com/kstenerud/go-concise-encoding/commit/3c2ead089fc75611e000c6df2f6c4a87244575ec
