### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by breck7** [kstenerud/concise-encoding#4]
The binary spec was clear and interesting and a pleasure to read. I enjoyed the feature and spec comparison tables on the readme. Solid work. Thanks for that.

One potential addition is Apache Arrow. It seems like perhaps there might be some overlap with their goals and yours in terms of addressing the data efficiency problem. I cannot remember if Apache Arrow has a human readable text version in the works. https://arrow.apache.org/.

There are also a few dialects of JSON that might be relevant (json5, json with comments, ...).

On the text encoding side—and my opinions here are far from the mainstream, maybe 1 in 100 programmers agree with me, so take them with a grain of salt— I see a lot of patterns I think we should avoid in the future. It's preserves all the unnecessary complexities of notations that were developed before our current crop of technologies. I would drop all the "unphonemes" -- characters that don't combine into sounds, things like brackets, quotations marks, the @'s, the 'u"'s, etc. In a future text encoding I want something that's easy to dictate to Siri or Alexa. Not necessarily that that is what I'll be doing, but if your encoding can pass the "Dictation Test" then that means it's also going to be good in an editor with autocomplete, and in particular the coming class of "superautcompletes" that use smart machine learning like TabNine.

Those are my 2 cents. Cool stuff!

**Comment by kstenerud** [comment]
Thanks for the input!

I'm not sure I follow on the "unphenomes"... The symbol characters are used to visually separate the data into containers, and to delimit the ends for some types. What would they be replaced with, and how human-readable would the result be?

For dictation, I think a simple verbal nomenclature would work, although you'd still need a way to "escape" when you mean to end a container and not put the delimiter inside of it...

**Comment by breck7** [comment]
> I'm not sure I follow on the "unphenomes".

Yes I was trying to come up with a new word for the concept I'm getting at. Perhaps there's a better word already out there that's eluding me. But my thinking is symbols like /*_[]""@#{} don't represent phonemes likes letters do and as a result don't compose well. I think perhaps a keyword based system may be more desirable `list 1 2 3` rather than `[1 2 3]`. My train of thought of course requires quite a lot of infra development, but that's where I think things could be header. It doesn't have to be keyword based though, you could perhaps do things via pattern matching if you carefully reduced the domains of the different types. Anyway this is probably not too relevant where you are taking things here, it's just the sort of thing I'm working on a lot so it came to my mind anyway.

> From what I can tell, Arrow seems to use flatbuffers, and also to use fixed-length record formats, which sacrifices size for access speed. That wouldn't be keeping with the same goals as concise encoding.

Yes. What I like about Arrow is the focus on the data science use case. I can parse a big 1GB file, do some processing, turn it into a binary blob, store that to disk, and then just load that into memory for later downstream data science tasks whether I'm using Python or R or C++.
